/**
 * Name / roster generator.
 *   npm run namegen                 -> print 20 sample fighter names
 *   npm run namegen -- --roster     -> (re)write data/roster/generated.json (250 fighters)
 *   npm run namegen -- --seed 77    -> use a different seed
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Rng } from '../src/core/rng';
import { generateFighter, GenOpts } from '../src/sim/generate';
import { ROOT } from './loadContent';
import type { NameTables, ManagerDef } from '../src/core/content';

const args = process.argv.slice(2);
const seedArg = args.indexOf('--seed');
const seed = seedArg >= 0 ? Number(args[seedArg + 1]) : 250;
const names: NameTables = JSON.parse(readFileSync(join(ROOT, 'data/roster/names.json'), 'utf8'));
const managers: ManagerDef[] = JSON.parse(readFileSync(join(ROOT, 'data/roster/managers.json'), 'utf8'));
const rng = Rng.fromSeed(seed);

const MEN = ['fly', 'bantam', 'feather', 'light', 'welter', 'middle', 'lightheavy', 'heavy'];
const WOMEN = ['wstraw', 'wfly', 'wbantam'];
const TIERS_M: GenOpts['tier'][] = [
  'elite', 'elite', 'contender', 'contender', 'contender', 'contender', 'gatekeeper', 'gatekeeper', 'gatekeeper', 'gatekeeper', 'gatekeeper',
  'journeyman', 'journeyman', 'journeyman', 'journeyman', 'journeyman', 'journeyman', 'journeyman', 'prospect', 'prospect', 'prospect', 'prospect', 'prospect', 'prospect', 'prospect',
];
const TIERS_W: GenOpts['tier'][] = [
  'elite', 'contender', 'contender', 'contender', 'gatekeeper', 'gatekeeper', 'gatekeeper', 'journeyman', 'journeyman', 'journeyman', 'journeyman', 'journeyman',
  'prospect', 'prospect', 'prospect', 'prospect', 'prospect',
];

const STRIP = ['status', 'promotion', 'storyHistory', 'careerLog', 'injuries', 'medSuspUntil', 'contract', 'legal', 'legalUntil', 'rivals', 'friends', 'beefReporters', 'beefWithYou', 'wounds', 'titleDefenses', 'scout'];

if (args.includes('--roster')) {
  const out: any[] = [];
  const used = new Set<string>();
  const managerIds = managers.map((m) => m.id);
  const gen = (division: string, gender: 'M' | 'W', tier: GenOpts['tier']) => {
    for (let tries = 0; tries < 20; tries++) {
      const f = generateFighter(rng, names, { division, gender, tier, managers: managerIds });
      const key = f.first + ' ' + f.last;
      if (used.has(key) || used.has(f.id)) continue;
      used.add(key);
      used.add(f.id);
      const o: any = { ...f, tier };
      for (const k of STRIP) delete o[k];
      out.push(o);
      return;
    }
  };
  for (const d of MEN) for (const t of TIERS_M) gen(d, 'M', t);
  for (const d of WOMEN) for (const t of TIERS_W) gen(d, 'W', t);
  writeFileSync(join(ROOT, 'data/roster/generated.json'), JSON.stringify({ note: 'Generated by npm run namegen -- --roster. Edit freely.', fighters: out }, null, 0).replace(/\},\{/g, '},\n{'));
  console.log(`Wrote ${out.length} fighters to data/roster/generated.json`);
} else {
  for (let i = 0; i < 20; i++) {
    const gender = rng.chance(0.2) ? 'W' : 'M';
    const f = generateFighter(rng, names, { division: gender === 'W' ? 'wfly' : rng.pick(MEN), gender, tier: 'journeyman' });
    console.log(`${f.first} "${f.nick}" ${f.last}  (${f.hometown}, ${f.country}) - ${f.styles.join('/')} - ${f.traits.join(', ')}`);
  }
}
