"""
Source for data/roster/marquee.json and data/roster/legends.json.
Run: python3 tools/roster_src.py
Parody characters carry `parody` (the real counterpart). They are never cast in
criminal / doping / abuse storylets (see SERIOUS_CATEGORIES in the engine).
Columns:
 id, first, last, nick, parody, gender, age, division, country, hometown,
 look (skin, hair, hairColor, beard, build, ears, tattoo, nose),
 skills (str, pow, wre, gra, car, chn, iq, dur, hrt, wcut),
 styles, traits, archetype, stance, signature, celebration, record (w, l),
 debutAct, startWith, potential, primeAge, moneyIQ, followers, bio
"""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')

M = [
 ("bro_bones","Jonny","Jonez","Bro Bones","Jon Jones","M",29,"lightheavy","USA","Rochester, NY",(4,1,0,1,1,2,1,0),(90,82,86,84,85,88,97,86,90,40),["Wrestler","Kickboxer"],["Showman","Perfectionist","Trash Talker"],"The GOAT","upright",["spinningElbow","obliqueKick"],"strut",(18,0),1,"free",98,31,40,3000000,
  "{first} has never truly lost a fight, unless you count the one he lost to a disqualification for elbows so nasty they were declared illegal. Spinning elbows, oblique kicks, and a reach that starts in one zip code and ends in another. Outside the cage, his schedule is 'chaotic' and his press availability is 'theoretical'."),
 ("conan_mcgrogan","Conan","McGrogan","The Notorious Invoice","Conor McGregor","M",27,"light","Ireland","Dublin",(0,2,1,3,1,1,3,0),(86,92,58,62,62,80,80,72,78,70),["Counter Striker","Showboat"],["Trash Talker","Showman","Business Savvy","Party Animal","Mercenary"],"The Loudmouth Superstar","karate",["leftHand","spinningWheelKick"],"billyStrut",(19,3),1,"free",92,28,75,9000000,
  "Former plumber's apprentice from Dublin who discovered that talking costs nothing and sells everything. One perfect left hand, one perfect mouth, and a bottomless appetite for equity stakes. Sells more pay-per-views than the rest of the division combined and will remind you of that in every negotiation, press conference and voicemail."),
 ("khabeeb","Khabeeb","Nurmagomedoof","The Eagle Scout","Khabib Nurmagomedov","M",28,"light","Dagestan (Russia)","Makhachkala",(1,2,0,3,1,3,0,1),(70,72,98,92,95,86,90,88,95,55),["Wrestler","Ground & Pound"],["Devout","Family First","Loyal"],"The Pious Grappler","wrestler",["chainWrestling","smesh"],"prays",(24,0),1,"free",95,30,80,4000000,
  "Wrestled bears as a child (allegedly, on camera). Mauls opponents for fifteen minutes while asking them, politely, to give up. Refuses alcohol sponsors, refuses to celebrate with champagne, and refuses to lose. His father's word is law. His mother's word is law with interest. May retire at the absolute peak because he promised someone."),
 ("izzy_adesanyuh","Izzy","Adesanyuh","The Last Style-Bender (Patent Pending)","Israel Adesanya","M",28,"middle","New Zealand","Auckland",(5,6,0,1,0,0,2,0),(94,80,52,60,82,78,90,74,80,45),["Counter Striker","Kickboxer"],["Showman","Trash Talker","Diva"],"The Anime Protagonist","sway",["matrixSlip","calfKick"],"animePose",(20,1),1,"free",93,29,65,2500000,
  "Kickboxing prodigy, anime enthusiast, and the most flexible trash talker in the sport. Walks out doing choreographed dances, fights like a ghost with a grudge, and treats every press conference like a rap battle he already won."),
 ("alex_pereirrah","Alex","Pereirrah","Stone Hands (Literal)","Alex Pereira","M",33,"middle","Brazil","Sao Paulo",(3,2,0,1,1,0,3,1),(92,97,52,55,72,82,82,85,90,70),["Kickboxer"],["Shy","Loyal","Devout"],"The Silent Executioner","upright",["leftHook","calfKick"],"bowAndArrow",(9,2),1,"free",93,32,60,1500000,
  "Former tire-shop worker who beat his demons and then beat everybody else. Says about four words per press conference and lets the left hook handle the rest. His hands have been described by doctors as 'geological'."),
 ("francis_ngonnagetpaid","Francis","N'Gonnagetpaid","The Predatory Lender","Francis Ngannou","M",33,"heavy","Cameroon","Douala",(5,0,0,1,2,1,0,1),(78,99,62,58,60,90,72,85,92,60),["Brawler"],["Business Savvy","Mercenary","Wholesome"],"The Pay Protester","upright",["uppercutOfGod","overhandRight"],"roar",(16,3),1,"free",88,32,85,2000000,
  "Worked in a sand mine, crossed a desert and a sea, slept in a parking garage, and now punches harder than a car accident. Very polite. Very calm. Will publicly and patiently explain, with charts, exactly how much you are underpaying him."),
 ("mack_hollowday","Mack","Hollowday","Blessed (Not Stressed)","Max Holloway","M",27,"feather","USA","Waianae, HI",(2,2,0,1,0,1,2,0),(92,72,62,70,97,92,88,90,96,55),["Pressure Striker"],["Wholesome","Showman","Trash Talker"],"The Wholesome Fan Favorite","bouncy",["pointToTheGround","volumePunching"],"shaka",(21,6),1,"free",91,29,70,1800000,
  "Throws 300 strikes a fight and talks to his opponent during most of them. Points at the floor in the last ten seconds and dares you to swing. Everyone loves him, which is a problem for marketing because nobody wants to watch him get punched."),
 ("dustin_poorrear","Dustin","Poor-Rear","The Diamond (Cubic Zirconia)","Dustin Poirier","M",29,"light","USA","Lafayette, LA",(0,2,1,3,1,2,1,2),(86,82,62,74,80,84,84,82,92,50),["Pressure Striker","Brawler"],["Family First","Wholesome","Business Savvy"],"The Hot Sauce Gentleman","bouncy",["leftHook","guillotine"],"hugsOpponent",(26,7),1,"free",88,30,72,1500000,
  "Louisiana's finest export after crawfish. Runs a hot sauce empire, a charity, and a never-ending series of wars against people who talked too much. Will fight anyone, anywhere, as long as there's a bottle of sauce on the table afterwards."),
 ("nate_diazz","Nate","Diazz","The Stockton Slapper","Nate Diaz","M",30,"welter","USA","Stockton, CA",(1,2,0,2,0,2,2,1),(80,66,50,86,96,86,78,80,95,40),["Brawler","Sub Hunter"],["Trash Talker","Hothead","Party Animal"],"The Stockton Stoner","brawler",["stocktonSlap","doubleMiddleFinger"],"shrug",(21,13),1,"free",80,30,55,3500000,
  "Seventeen hours of cardio, zero filter. Slaps opponents mid-combination to remind them they're being disrespected. Shows up to press conferences late, leaves early, and somehow always wins the press conference."),
 ("jorge_massvidal","Jorge","Mass-Vidal","Gamebred (Store-Bought)","Jorge Masvidal","M",32,"welter","USA","Miami, FL",(2,1,0,3,1,2,2,2),(84,84,70,66,72,82,80,78,85,55),["Brawler","Counter Striker"],["Trash Talker","Showman","Political"],"The Backyard Legend","upright",["flyingKnee","threePieceAndASoda"],"strut",(35,15),1,"free",78,31,60,2000000,
  "Learned to fight in Miami backyards and never left the backyard emotionally. Famous for a five-second flying knee and a post-fight description involving a soda. Delivers trash talk like a mob boss reading a grocery list."),
 ("colby_covingtonne","Colby","Covingtonne","Chaos Theory","Colby Covington","M",30,"welter","USA","Clovis, CA",(0,2,4,0,1,3,1,0),(72,64,90,74,97,82,80,82,86,55),["Wrestler","Pressure Striker"],["Trash Talker","Political","Showman"],"The Professional Heel","wrestler",["cardioMachine","doubleLeg"],"mockery",(17,4),1,"free",86,30,60,1600000,
  "Says the most offensive thing in any room he walks into, then wrestles you for 25 minutes without breathing hard. Fans pay to see him lose. He is fine with that, as long as they pay."),
 ("kamaru_usmansplain","Kamaru","Usmansplain","The Nigerian Nightmare (Mild)","Kamaru Usman","M",31,"welter","Nigeria","Auchi",(5,1,0,1,2,1,0,0),(82,84,94,72,92,86,88,88,88,55),["Wrestler","Boring But Effective"],["Business Savvy","Devout","Loyal"],"The Inevitable Champion","wrestler",["jabOfDeath","cageGrind"],"gunShow",(19,1),1,"free",90,31,85,1200000,
  "Former NCAA wrestler who went from 'boring' to 'terrifying' in the space of one jab. Grinds you against the fence until you question your career choices. Big on business, bigger on the gospel, biggest on reminding you he's undefeated in the division."),
 ("shawn_omallard","Shawn","O'Mallard","Sugar-Free","Sean O'Malley","M",25,"bantam","USA","Helena, MT",(0,4,5,1,0,0,3,0),(88,82,52,62,76,70,84,70,78,55),["Counter Striker","Showboat"],["Streamer","Showman","Party Animal","Clout Chaser"],"The Meme Kid Made Good","handsLow",["pullCounter","switchKick"],"middleFingerPose",(14,1),1,"free",92,27,65,4000000,
  "Rainbow hair, rainbow tattoos, rainbow knockouts. Streams everything, wears everything, and treats striking like an art project. Got famous on a reality show and stayed famous by putting people to sleep on the way down."),
 ("charles_olivegarden","Charles","Olive-Garden","Do Bronx (Do Buffet)","Charles Oliveira","M",29,"light","Brazil","Guaruja",(2,2,0,1,1,1,3,0),(80,78,66,98,82,74,84,74,94,60),["Sub Hunter","Muay Thai"],["Devout","Family First","Wholesome"],"The Submission Machine","upright",["kneeToTheBody","backTake"],"prays",(30,8),1,"free",90,30,60,1300000,
  "Has more submission wins than most fighters have fights. Grew up in a favela, survived a childhood illness doctors said he wouldn't, and now strangles people with a smile on his face and Jesus on his shorts."),
 ("islam_makeacheck","Islam","Make-A-Check","The Chosen One (To Do Paperwork)","Islam Makhachev","M",30,"light","Dagestan (Russia)","Makhachkala",(1,2,0,3,1,3,0,0),(84,76,96,94,92,84,90,86,90,55),["Wrestler","Sub Hunter"],["Devout","Loyal","Shy"],"The Heir","wrestler",["armTriangle","headKick"],"prays",(23,1),1,"free",95,30,75,1400000,
  "Trained under the Eagle Scout since childhood and talks about him like a holy text. Quiet, devout, and capable of folding you in half like a lawn chair."),
 ("alex_volkannoski","Alexander","Volkan-NoSki","The Great (Average Height)","Alexander Volkanovski","M",30,"feather","Australia","Wollongong",(0,1,1,1,1,1,1,0),(90,80,78,74,94,84,94,84,94,55),["Pressure Striker"],["Wholesome","Family First","Perfectionist"],"The Rugby Dad Champion","bouncy",["legKicks","volume"],"wavesToKids",(22,1),1,"free",93,30,80,900000,
  "Former rugby player who was 214 pounds and decided to be 145. Fights with a clipboard brain and a family-man heart. Responds to trash talk with a slightly confused smile and then a seven-round beating in five rounds."),
 ("ilia_topuria","Ilia","Top-Uria","El Matador (Of Egos)","Ilia Topuria","M",26,"feather","Georgia","Tbilisi",(1,2,0,1,1,1,1,0),(90,92,82,84,84,86,88,84,90,60),["Pressure Striker","Sub Hunter"],["Trash Talker","Showman","Perfectionist"],"The Predictor","upright",["predictsTheRound","leftHook"],"pointsAtWatch",(13,0),1,"free",95,28,70,1200000,
  "Predicts the round, predicts the punch, predicts the facial expression of the person he's about to knock out. Has so far been right so often it's becoming a legal issue for bookmakers."),
 ("tom_aspinall","Tom","Aspin-All","The Bargain Bin Brit","Tom Aspinall","M",29,"heavy","England","Wigan",(0,2,1,1,2,1,0,0),(88,88,80,86,82,82,88,84,86,55),["Pressure Striker","Sub Hunter"],["Wholesome","Loyal"],"The Quick Finisher","upright",["fastHands","pivotHook"],"none",(13,3),1,"free",93,30,75,800000,
  "A heavyweight who moves like a welterweight and talks like the nicest bloke at your local pub. Finishes fights before the crowd has found their seats."),
 ("leon_edwardz","Leon","Edwardz","Rocky (Balboa's Accountant)","Leon Edwards","M",30,"welter","England","Birmingham",(4,1,0,0,1,0,1,0),(86,80,74,74,86,82,88,80,90,55),["Counter Striker"],["Shy","Family First"],"The Patient Counter-Puncher","upright",["headKick","counterJab"],"none",(20,3),1,"free",88,30,75,700000,
  "Born in Jamaica, raised in Birmingham, famous for one head kick that sent half the sport into hysterics. Quiet, measured, and deeply unbothered by everyone who calls him boring."),
 ("belal_muhammadad","Belal","Muhammadad","Remember the Name (Please)","Belal Muhammad","M",34,"welter","USA","Chicago, IL",(2,2,0,3,1,1,0,0),(80,64,84,74,92,82,88,84,88,55),["Point Fighter","Wrestler"],["Devout","Trash Talker","Family First"],"The Grinder","upright",["chainWrestling","volume"],"prays",(23,3),1,"free",84,33,70,500000,
  "Spent years being told he was boring, then won the belt boringly, then held it boringly. Argues with strangers online for sport and has never lost an argument according to himself."),
 ("drickus_dupleasey","Drickus","Du Pleasey","Stillknocks (Still Awkward)","Dricus du Plessis","M",29,"middle","South Africa","Pretoria",(0,2,3,0,2,1,1,1),(78,88,82,78,88,86,74,90,95,60),["Brawler","Wrestler"],["Trash Talker","Showman","Loyal"],"The Awkward Destroyer","brawler",["awkwardFlurry","backTake"],"flexes",(20,2),1,"free",89,30,65,600000,
  "Fights like a man falling down a staircase on purpose and somehow lands on top every time. Nobody can explain his style, including his coaches."),
 ("sean_strictlyland","Sean","Strictlyland","Tarzan (Unfiltered)","Sean Strickland","M",31,"middle","USA","Anaheim, CA",(0,1,4,0,1,1,2,1),(84,66,72,70,92,84,80,84,86,55),["Point Fighter","Pressure Striker"],["Trash Talker","Streamer","Political"],"The Unfiltered Jabber","upright",["philly shell","jabJabJab"],"none",(28,6),1,"free",84,31,55,900000,
  "Jabs you for 25 minutes and talks for 25 hours. Every press conference is a live hostage situation for the PR team. Streams his sparring, his opinions and his opinions about your opinions."),
 ("justin_gatchy","Justin","Gatchy","The Highlight Reel (Unedited)","Justin Gaethje","M",31,"light","USA","Safford, AZ",(0,1,2,2,1,2,0,2),(84,90,84,50,82,80,74,86,96,55),["Brawler","Pressure Striker"],["Wholesome","Hothead"],"The War Machine","brawler",["legKicks","overhandRight"],"backflip",(24,4),1,"free",84,30,70,800000,
  "D1 wrestler who refuses to wrestle. Fights exclusively in the pocket, chops legs like firewood, and treats every fight like a car crash he paid tickets for."),
 ("paddy_pimpblett","Paddy","Pimpblett","The Baddy (Snack-Weight)","Paddy Pimblett","M",27,"light","England","Liverpool",(0,3,4,0,2,1,1,0),(72,72,62,88,74,76,72,78,86,90),["Sub Hunter","Brawler"],["Showman","Party Animal","Clout Chaser"],"The Scouse Sensation","brawler",["rearNakedChoke","bigOverhand"],"shushesCrowd",(20,3),1,"free",82,28,55,2000000,
  "Liverpool's loudest export since the Beatles. Balloons fifty pounds between fights and posts every cheeseburger. Fans adore him, critics doubt him, and he is perfectly happy to sell both of them tickets."),
 ("michael_chandelier","Michael","Chandelier","Iron (Supplement)","Michael Chandler","M",34,"light","USA","High Ridge, MO",(0,2,4,0,1,1,0,0),(80,90,86,62,74,76,72,80,94,55),["Brawler","Wrestler"],["Devout","Wholesome","Showman"],"The Motivational Speaker","bouncy",["overhandRight","frontKick"],"crossesHimself",(23,8),1,"free",78,31,72,700000,
  "Gives speeches after wins, speeches after losses, and speeches to the cashier at the grocery store. Comes out of the corner like a golden retriever on espresso."),
 ("derrick_loose","Derrick","Loose","The Sweaty Beast","Derrick Lewis","M",34,"heavy","USA","Houston, TX",(5,0,0,3,2,1,1,1),(70,97,58,48,48,90,60,86,86,70),["Brawler"],["Prankster","Wholesome","Lazy"],"The Funniest Man in the Building","brawler",["uppercutBomb","sleepyDefense"],"takesShirtOff",(26,10),1,"free",70,32,60,1200000,
  "Holds the record for most knockouts and most quotable post-fight interviews. Looks exhausted at all times, then knocks you out with one swing while appearing to fall asleep."),
 ("tony_fergusoff","Tony","Fergusoff","El Cucuy (The Boogeyman, Allegedly)","Tony Ferguson","M",33,"light","USA","Oxnard, CA",(2,2,0,4,0,2,0,2),(80,76,74,88,94,82,66,84,96,60),["Sub Hunter","Brawler"],["Perfectionist","Gym Rat","Paranoid"],"The Eccentric Mad Scientist","karate",["darceChoke","imanariRoll"],"none",(25,3),1,"free",76,31,55,900000,
  "Trains by walking on his hands, juggling medicine balls and doing things with a kettlebell that would make a physiotherapist faint. Talks in riddles. Fights like a slasher movie."),
 ("henry_sayhoodoo","Henry","Say-Hoodoo","Triple C (Cringe Champion)","Henry Cejudo","M",31,"bantam","USA","Phoenix, AZ",(2,2,0,4,1,1,0,0),(78,72,94,76,86,80,86,82,88,55),["Wrestler"],["Showman","Trash Talker","Clout Chaser"],"The King of Cringe","wrestler",["doubleLeg","kneeToBody"],"crownGesture",(16,2),1,"free",86,30,70,800000,
  "Olympic gold medallist who decided his real talent was cringe. Wears a crown to press conferences, calls himself the greatest of all time, and occasionally backs it up, which is the most annoying part."),
 ("merab_dvalichill","Merab","Dvali-Chill-Vili","The Machine (Cardio Edition)","Merab Dvalishvili","M",31,"bantam","Georgia","Tbilisi",(1,0,0,1,1,3,0,0),(70,62,98,74,99,86,82,88,95,55),["Wrestler","Boring But Effective"],["Wholesome","Gym Rat","Prankster"],"The Unstoppable Motor","wrestler",["takedown60times"],"carriesOpponent",(15,4),1,"free",90,31,70,900000,
  "Shoots takedowns at a rate that should be studied by NASA. Doesn't get tired, doesn't stop smiling, and once tried to carry a teammate around the cage after a win."),
 ("aljamain_sterlingsilver","Aljamain","Sterling-Silver","Funk Master (Funk Apprentice)","Aljamain Sterling","M",28,"bantam","USA","Uniondale, NY",(4,6,0,1,0,1,1,0),(76,62,84,92,86,78,86,78,84,55),["Sub Hunter","Wrestler"],["Trash Talker","Streamer","Showman"],"The Backpack Specialist","bouncy",["backTake","bodyTriangle"],"none",(22,4),1,"free",87,29,70,600000,
  "Climbs onto opponents' backs like a determined hiker and refuses to get off. Hosts a podcast where he replies to every single critic personally."),
 ("petr_yawn","Petr","Yawn","No Mercy (Some Mercy)","Petr Yan","M",28,"bantam","Russia","Dudinka",(0,1,4,0,1,1,1,1),(92,82,80,72,86,86,88,84,88,55),["Pressure Striker"],["Shy","Loyal"],"The Stoic Boxer","upright",["bodyShots","switchStance"],"none",(16,3),1,"free",90,29,70,500000,
  "Grew up in the Russian Arctic, where the boxing gyms are colder than his stare. Doesn't trash talk, doesn't smile, doesn't stop throwing to the body."),
 ("brandon_morenot","Brandon","Morenot","The Assassin Baby","Brandon Moreno","M",26,"fly","Mexico","Tijuana",(2,1,0,1,1,1,1,0),(84,70,74,82,88,82,84,80,92,55),["Pressure Striker","Sub Hunter"],["Wholesome","Showman","Family First"],"The Underdog Hero","bouncy",["guillotine","bodyJab"],"mexicanFlag",(18,5),1,"free",88,28,70,700000,
  "Got cut, came back, became champion, and cried on national television in the most relatable way possible. All of Mexico's flyweight hopes live in his tiny tank top."),
 ("alexandre_panterajoe","Alexandre","Pantera-Joe","The Cannibal (Vegetarian)","Alexandre Pantoja","M",32,"fly","Brazil","Natal",(2,2,0,2,0,1,2,1),(78,68,82,90,86,82,84,80,92,55),["Sub Hunter","Pressure Striker"],["Wholesome","Devout"],"The Scramble King","bouncy",["backTake","rearNakedChoke"],"prays",(27,5),1,"free",84,32,60,300000,
  "Wins every scramble, every chaotic exchange and every staring contest. Calls himself the Cannibal and then apologizes for it."),
 ("robert_wittyacker","Robert","Wittyacker","The Reaper (Part-Time)","Robert Whittaker","M",30,"middle","Australia","Sydney",(2,2,0,1,1,1,1,0),(88,84,80,72,88,82,88,84,94,55),["Counter Striker","Kickboxer"],["Wholesome","Family First"],"The Nicest Killer","karate",["blitz","headKick"],"none",(23,6),1,"free",88,30,72,500000,
  "Karate-based blitzer, devoted dad, and possibly the most polite man to ever deliver a head kick. Has a laugh that sounds like an apology."),
 ("khamzat_chimaye","Khamzat","Chim-Aye","Borz (Wolf, Bored)","Khamzat Chimaev","M",28,"welter","Sweden","Stockholm",(1,2,0,3,2,2,0,0),(84,90,96,86,76,86,80,86,90,75),["Wrestler","Ground & Pound"],["Trash Talker","Devout","Injury Prone"],"The Smash-Everybody Machine","wrestler",["doubleLeg","smash"],"walksAway",(12,0),2,"free",96,29,65,2500000,
  "Says he'll smash everybody, then does, then asks for three more fights the same night. Wrestles like a hurricane wearing a weighted vest. Shows up sick more often than a kindergarten teacher."),
 ("valentina_shevchenkont","Valentina","Shev-Chenko-N't","Bullet (Train)","Valentina Shevchenko","W",30,"wfly","Kyrgyzstan","Bishkek",(0,7,5,0,0,0,0,0),(92,78,82,86,88,84,96,84,92,55),["Muay Thai","Counter Striker"],["Perfectionist","Shy","Gym Rat"],"The Untouchable Queen","upright",["spinningBackKick","counterLeft"],"dances",(23,4),3,"free",94,31,80,1200000,
  "Muay Thai world champion before most of her opponents were born. Practices shooting, tango and spinning back kicks, all with lethal precision. Dances after wins like a ballroom champion who just hospitalized someone."),
 ("zhang_weileap","Zhang","Wei-Leap","Magnum (Of Champagne)","Zhang Weili","W",31,"wstraw","China","Handan",(0,7,0,0,1,0,0,0),(90,84,82,80,90,86,86,86,92,55),["Pressure Striker","Judoka"],["Perfectionist","Loyal","Wholesome"],"The Pressure Cooker","upright",["spinningBackfist","suplex"],"bows",(23,3),3,"free",92,31,75,1000000,
  "Former receptionist who decided she'd rather throw people than answer phones. Relentless pressure, explosive throws, and a spinning backfist that has its own fan account."),
 ("rose_namastejunas","Rose","Namaste-Junas","Thug Daisy","Rose Namajunas","W",28,"wstraw","USA","Milwaukee, WI",(0,1,4,0,0,0,0,0),(88,72,72,82,84,80,90,80,86,55),["Counter Striker"],["Wholesome","Shy","Perfectionist"],"The Zen Warrior","sway",["headKick","counterRight"],"none",(12,5),3,"free",88,29,70,600000,
  "Shaved head, quiet voice, and a pre-fight mantra that sounds like a meditation app. Then she head-kicks someone into another tax bracket."),
 ("julianna_painya","Julianna","Pain-Ya","The Venezuelan Vixen (Volume Discount)","Julianna Pena","W",32,"wbantam","USA","Spokane, WA",(2,5,1,0,1,1,1,0),(72,70,82,84,84,82,72,82,90,55),["Brawler","Sub Hunter"],["Trash Talker","Showman"],"The Trash-Talking Underdog","brawler",["takedown","rearNakedChoke"],"pointsAtCrowd",(11,5),3,"free",78,31,60,500000,
  "Trash talks like she's already won and fights like she believes it. Pulled off one of the biggest upsets in history and has been talking about it ever since, with full justification."),
 ("kayla_harrowson","Kayla","Harrowson","The Judo Hammer","Kayla Harrison","W",32,"wbantam","USA","Middletown, OH",(0,2,4,0,2,1,0,0),(68,80,92,88,86,84,82,86,90,85),["Judoka","Ground & Pound"],["Perfectionist","Loyal"],"The Olympic Juggernaut","wrestler",["hipThrow","armTriangle"],"none",(16,1),3,"free",88,31,75,400000,
  "Two-time Olympic judo gold medallist who throws women around like laundry. Cutting weight is the only opponent who's ever given her trouble."),
 ("gilbert_burnt","Gilbert","Burnt","Durinho (Durin-HO-HO)","Gilbert Burns","M",32,"welter","Brazil","Rio de Janeiro",(2,2,0,1,1,2,1,0),(78,82,74,94,78,82,80,82,90,55),["Sub Hunter","Brawler"],["Wholesome","Showman"],"The BJJ World Champ Who Wants to Bang","bouncy",["overhandRight","armTriangle"],"none",(22,6),1,"free",82,31,65,500000,
  "World champion in jiu-jitsu who prefers to stand and swing anyway. Cheerful, loud, and permanently trying to call out someone bigger than him."),
 ("jiri_prochazkaboom","Jiri","Pro-Chaz-Ka-Boom","BJP (Bushido Jiri Philosophy)","Jiri Prochazka","M",29,"lightheavy","Czechia","Hostice",(0,5,1,0,1,0,0,0),(88,88,62,62,76,74,74,82,94,55),["Brawler","Kickboxer"],["Perfectionist","Shy"],"The Samurai of Chaos","handsLow",["spinningBackfist","flyingKnee"],"bows",(29,3),1,"free",90,30,55,700000,
  "Trains by reading samurai philosophy and fighting in forests. Keeps his hands at his waist and his chin in danger, and wins anyway in the most chaotic way possible."),
 ("magomed_ankleayev","Magomed","Ankle-Ayev","Boring But Dangerous","Magomed Ankalaev","M",30,"lightheavy","Dagestan (Russia)","Makhachkala",(1,1,0,3,1,2,0,0),(84,82,86,72,86,84,90,86,86,55),["Boring But Effective","Kickboxer"],["Shy","Devout"],"The Fun Vacuum","upright",["counterLeft","kickCatch"],"none",(19,1),1,"free",88,31,70,200000,
  "So technically sound he makes main events feel like tax seminars. Nobody wants to fight him. Nobody wants to watch him. Nobody can beat him."),
 ("ciryl_gain","Ciryl","Gain","Bon Gamin (Bon Appetit)","Ciryl Gane","M",31,"heavy","France","La Roche-sur-Yon",(4,1,0,1,1,0,0,0),(90,74,62,68,86,80,90,80,82,55),["Kickboxer","Point Fighter"],["Wholesome","Shy"],"The Ballet Heavyweight","bouncy",["switchKick","footwork"],"none",(12,2),1,"free",88,31,72,400000,
  "A heavyweight who moves like a dancer and speaks French softly at press conferences. Opponents can't hit him. Fans can't tell if they're bored or mesmerized."),
 ("curtis_blades","Curtis","Blades","Razor (Disposable)","Curtis Blaydes","M",30,"heavy","USA","Chicago, IL",(5,0,0,1,2,2,0,0),(70,86,94,70,80,78,74,84,84,60),["Wrestler","Ground & Pound"],["Prankster","Wholesome"],"The Takedown Truck","wrestler",["doubleLeg","elbowsFromTop"],"none",(17,4),1,"free",82,31,65,300000,
  "Shoots double legs like his life depends on them and says genuinely funny things in interviews that get him in mild trouble with nobody in particular."),
 ("bo_nickelanddime","Bo","Nickel-And-Dime","Bo-Dacious","Bo Nickal","M",26,"middle","USA","State College, PA",(0,2,4,0,1,1,0,0),(64,76,98,90,86,78,80,78,84,55),["Wrestler","Sub Hunter"],["Devout","Trash Talker","Wholesome"],"The Wrestling Prodigy","wrestler",["armTriangle","doubleLeg"],"none",(6,0),2,"free",97,30,75,600000,
  "Three-time NCAA champion who believes he's the best fighter alive after six pro fights. He might be right. He might be very, very wrong. Everyone wants to find out."),
 ("jake_pall","Jake","Pall","The Problem Child (Now A Problem Adult)","Jake Paul","M",26,"lightheavy","USA","Cleveland, OH",(0,2,4,1,1,0,2,0),(68,74,30,24,66,70,62,70,72,55),["Brawler","Showboat"],["Clout Chaser","Streamer","Showman","Business Savvy","Trash Talker"],"The Influencer Crossover","upright",["overhandRight","rolexBet"],"flexes",(8,1),2,"free",65,30,90,30000000,
  "YouTube star turned boxer who would very much like to fight in your cage, ideally against someone forty years old with two broken legs. Brings forty million followers, his own energy drink, and a lawyer for every occasion."),
 ("bryce_mitchhell","Bryce","Mitch-Hell","Thug Gentle","Bryce Mitchell","M",28,"feather","USA","Cove, AR",(0,7,4,3,0,1,0,0),(68,62,82,92,86,80,74,80,88,55),["Sub Hunter","Wrestler"],["Conspiracy Poster","Family First","Gym Rat"],"The Farm-Boy Philosopher","wrestler",["twister","backTake"],"none",(16,2),1,"free",82,29,60,300000,
  "Arkansas farm boy who hunts his own food, builds his own house and does a twister submission for fun. Has opinions on the shape of the planet that keep the PR team awake at night."),
 ("arman_tsaryoucant","Arman","Tsar-You-Can't","Ahalkalakets (Spell It)","Arman Tsarukyan","M",27,"light","Armenia","Akhalkalaki",(1,2,0,1,1,1,0,0),(82,78,92,84,88,82,86,84,88,55),["Wrestler","Pressure Striker"],["Gym Rat","Trash Talker"],"The Patient Contender","wrestler",["chainWrestling","flyingKnee"],"none",(21,3),1,"free",92,30,70,400000,
  "The most avoided man in the division, according to the most avoided man in the division. Wrestles at a pace that should be illegal."),
 ("jack_dellamadeleine","Jack","Della Madeleine","JDM (Just Dropped Men)","Jack Della Maddalena","M",27,"welter","Australia","Perth",(0,2,2,1,1,0,1,0),(92,84,66,68,86,84,84,82,90,55),["Pressure Striker"],["Wholesome","Loyal"],"The Boxing Surfer","upright",["bodyHook","combination"],"none",(16,2),1,"free",92,30,70,500000,
  "Perth's smoothest boxer. Talks like a surfer, punches like a jackhammer, and politely apologizes to referees for making them work."),
 ("shavkat_rockmonov","Shavkat","Rock-Monov","Nomad (No Mad)","Shavkat Rakhmonov","M",29,"welter","Kazakhstan","Shymkent",(1,1,0,3,1,1,0,0),(84,84,86,90,84,84,88,86,88,55),["Pressure Striker","Sub Hunter"],["Shy","Devout"],"The Finisher","upright",["guillotine","headKick"],"none",(18,0),1,"free",93,30,70,300000,
  "Every fight, every finish. Speaks softly, chokes firmly. The kind of man other contenders schedule dentist appointments to avoid."),
 ("mvp_paige","Michael","Paige","Venim (Not a Sponsor)","Michael 'Venom' Page","M",36,"welter","England","London",(4,0,0,0,0,0,1,0),(86,80,48,56,80,72,80,72,74,55),["Showboat","Kickboxer"],["Showman","Trash Talker","Mercenary"],"The Rival-Promotion Defector","handsLow",["flyingKnee","pointsAtHead"],"pokemonPose",(22,3),2,"bellatrix",80,30,65,900000,
  "Point-karate wizard who keeps his hands at his hips and his ego in orbit. Spent a decade at a rival promotion being the most entertaining thing on their cards, and wants you to pay for that history."),
 ("patricio_freirepit","Patricio","Freire-Pit","Pitbull (Chihuahua Mix)","Patricio Freire","M",32,"feather","Brazil","Natal",(2,1,0,1,1,1,1,0),(86,84,78,84,84,82,88,82,90,55),["Pressure Striker"],["Loyal","Family First"],"The Rival Promotion's Franchise","upright",["overhandRight","guillotine"],"none",(34,6),1,"bellatrix",82,30,60,300000,
  "The rival league's two-division champion and franchise face. Loyal to them, which means he's the hardest man in the sport to poach and the most satisfying to sign."),
 ("cris_cyberborg","Cris","Cyber-Borg","Cyborg (Firmware Update)","Cris Cyborg","W",33,"wbantam","Brazil","Curitiba",(2,1,0,0,2,1,1,1),(88,92,72,74,82,86,78,88,90,85),["Pressure Striker","Muay Thai"],["Showman","Mercenary"],"The Unstoppable Force","brawler",["muayThaiClinch","knee"],"flexes",(26,2),3,"bellatrix",80,33,70,1200000,
  "The most feared woman in the history of the sport. Has fought for every promotion that would pay her and destroyed everyone they put in front of her."),
 # ---- originals (not parodies): these carry the darker scandal archetypes
 ("dorian_blackwood","Dorian","Blackwood","Bad Decisions",None,"M",27,"lightheavy","USA","Albany, NY",(3,2,0,1,1,2,2,1),(88,84,84,80,82,86,90,84,86,45),["Wrestler","Kickboxer"],["Party Animal","Reckless Driver","Hothead","Showman"],"The Troubled GOAT","upright",["spinningElbow","obliqueKick"],"strut",(17,0),1,"free",97,30,25,1200000,
  "A generational talent who has never truly lost a fight and has never truly won one against himself. The cage is the only place his life makes sense. Everywhere else, he's a weekly emergency meeting."),
 ("tanner_brix","Tanner","Brix","No Context",None,"M",30,"welter","USA","Boise, ID",(0,1,4,1,1,1,2,0),(80,74,78,72,82,80,76,80,82,55),["Pressure Striker"],["Streamer","Conspiracy Poster","Political","Trash Talker"],"The Unfiltered Podcaster","upright",["jabJabJab"],"none",(19,5),1,"us",80,30,45,700000,
  "Good fighter. Great podcast numbers. Terrible judgment. Hosts a four-hour stream called 'No Context' where every week he says something that costs you a sponsor."),
 ("gus_petrakis","Gus","Petrakis","The Toll Booth",None,"M",33,"light","USA","Tarpon Springs, FL",(1,1,0,3,2,3,1,2),(78,76,80,76,84,92,86,92,96,50),["Boring But Effective","Wrestler"],["Loyal","Gym Rat","Family First"],"The Moneyweight Gatekeeper","wrestler",["cageGrind"],"none",(24,9),1,"us",75,30,70,40000,
  "Every prospect has to pay the toll. Thirty-three fights, zero highlight reels, and a chin carved out of a boat anchor. Nobody wants to fight him and nobody wants to watch him, which is exactly why you need him."),
 ("rudy_okonjo","Rudy","Okonjo","Buffet Killer",None,"M",28,"feather","USA","Houston, TX",(5,0,0,1,2,1,1,0),(82,84,70,66,70,84,72,82,84,96),["Brawler"],["Party Animal","Wholesome","Lazy"],"The Weight-Miss Repeat Offender","brawler",["overhandRight"],"none",(14,4),1,"us",80,28,40,90000,
  "A legitimately dangerous featherweight trapped in the body of a man who has never said no to a buffet. Misses weight with the reliability of a Swiss watch."),
 ("jayden_crump","Jayden","Crump","Viral",None,"M",22,"bantam","USA","Tulsa, OK",(0,4,4,0,0,0,1,0),(66,86,40,36,62,66,52,66,74,55),["Brawler","Showboat"],["Clout Chaser","Streamer","Party Animal"],"The Meme Kid","handsLow",["spinningBackfist"],"backflip",(5,0),1,"free",82,27,30,2400000,
  "Went viral for a spinning backfist knockout in a regional show that took place in a Waffle Hut parking lot. Zero fundamentals, two million followers, and a manager who is also his roommate."),
 ("kevin_hargrove_jr","Kevin","Hargrove Jr.","Kev Jr.",None,"M",24,"middle","USA","Toledo, OH",(0,2,3,0,1,1,0,0),(72,74,74,70,78,72,68,74,70,55),["Wrestler"],["Shy","Loyal"],"The Dad Who Lives Through His Son","wrestler",["doubleLeg"],"none",(8,2),1,"us",85,29,60,30000,
  "A shy, decent kid with real talent and a father who screams at referees, judges, promoters and occasionally clouds. Kevin Sr. is his manager, coach, nutritionist and only source of stress."),
 ("bianca_ferreira","Bianca","Ferreira","Bulldozer",None,"W",27,"wbantam","Brazil","Recife",(3,6,0,0,1,1,2,0),(80,84,72,76,80,82,70,80,88,60),["Brawler","Pressure Striker"],["Party Animal","Hothead","Showman"],"The Wild Card","brawler",["knee"],"flexes",(12,2),3,"free",86,29,35,500000,
  "Fights like she's late for something and parties like the something is cancelled. Equally likely to win a fight-of-the-night bonus and to start a fight at the after-party."),
 ("silas_merriweather","Silas","Merriweather","The Accountant",None,"M",31,"welter","USA","Des Moines, IA",(0,2,2,0,1,0,0,0),(76,70,80,82,84,78,90,78,82,55),["Boring But Effective","Sub Hunter"],["Business Savvy","Wholesome","Perfectionist"],"The Accountant","upright",["arm triangle"],"none",(15,3),1,"us",78,30,98,20000,
  "Ex-CPA who still does half the roster's taxes and has started asking very specific questions about yours."),
 ("mateo_varga","Mateo","Varga","Mercenary",None,"M",29,"middle","Mexico","Tijuana",(2,1,0,4,1,2,2,1),(82,82,78,76,80,82,80,82,84,55),["Pressure Striker"],["Mercenary","Business Savvy","Trash Talker"],"The Defector","upright",["bodyHook"],"none",(20,4),1,"golden_promotions",82,29,80,300000,
  "Has fought for five promotions in five years and left each one with a lawsuit and a highlight reel."),
 ("cody_rawlings","Cody","Rawlings","Dip Can",None,"M",29,"light","USA","Odessa, TX",(0,2,4,2,1,1,2,1),(78,80,76,66,72,82,66,80,84,60),["Brawler"],["Reckless Driver","Gambler","Party Animal","Hothead"],"The Texas Tornado","brawler",["overhandRight"],"none",(16,6),1,"us",76,29,20,60000,
  "Owns four trucks, three of which are impounded. Bets his purse on himself, then on the co-main, then on the NFL. A delight in the cage and a liability everywhere else."),
 ("dmitri_volkhov","Dmitri","Volkhov","The Tax Audit",None,"M",30,"heavy","Russia","Omsk",(0,1,6,3,2,2,1,2),(76,92,80,70,66,88,74,90,88,60),["Brawler","Wrestler"],["Gambler","Business Savvy","Paranoid"],"The Mystery Heavyweight","brawler",["overhandRight"],"none",(18,3),1,"free",82,31,60,100000,
  "Nobody is sure where his money comes from, including the tax authorities of three countries. Hits like a falling safe."),
 ("brayden_pruitt","Brayden","Pruitt","Southern Fried",None,"M",26,"light","USA","Mobile, AL",(0,2,4,1,1,1,1,0),(78,80,78,72,78,80,70,80,86,55),["Brawler","Wrestler"],["Party Animal","Reckless Driver","Trash Talker"],"The Good Ol' Boy","brawler",["overhandRight"],"backflip",(12,2),1,"us",84,28,25,250000,
  "A good ol' boy with a heart of gold, a truck with no muffler, and a criminal record that is mostly traffic court. Mostly."),
]

L = [
 ("andersun_silvah","Andersun","Silvah","The Spider (Daddy Long Legs)","Anderson Silva","M",44,"middle","Brazil","Curitiba",(3,0,0,2,0,0,1,0),(82,74,52,64,62,64,92,62,80,50),["Counter Striker","Showboat"],["Showman","Wholesome"],"The Comeback Legend","handsLow",["matrixLean","frontKick"],"dances",(34,11),"One more fight. Always one more fight. Fifty years old and still insists he's 'feeling 25'."),
 ("georges_stpierrot","Georges","St-Pierrot","Rush (Hour)","Georges St-Pierre","M",42,"welter","Canada","Montreal, QC",(0,1,0,0,1,0,0,0),(84,72,90,84,80,78,96,78,88,55),["Wrestler","Point Fighter"],["Perfectionist","Wholesome","Business Savvy"],"The Perfect Retiree","karate",["superman","doubleLeg"],"none",(26,2),"The most polite champion in history. Retired at the top and is 'definitely, absolutely not' coming back. (He might be coming back.)"),
 ("fyodor_emelianankle","Fyodor","Emelian-Ankle","The Last Emperor (Of Sweaters)","Fedor Emelianenko","M",47,"heavy","Russia","Stary Oskol",(0,2,1,0,2,1,0,1),(78,84,74,84,60,70,90,68,88,55),["Brawler","Sub Hunter"],["Shy","Devout","Loyal"],"The Quiet Emperor","upright",["russianHook"],"none",(40,7),"Undefeated for a decade in an era before anyone kept track. Wears a sweater that has its own legend."),
 ("chuck_lidd","Chuck","Lid-Dell","The Iceman (Cometh Back)","Chuck Liddell","M",54,"lightheavy","USA","Santa Barbara, CA",(0,4,0,0,1,2,2,1),(76,84,60,52,50,56,72,58,80,55),["Brawler","Counter Striker"],["Party Animal","Showman"],"The Mohawk Legend","upright",["overhandRight"],"none",(21,9),"Mohawk, tattoo on the head, and an overhand right that defined an era. Comebacks have not gone well."),
 ("randy_couturealy","Randy","Couture-Al","The Natural (Flavors)","Randy Couture","M",60,"heavy","USA","Everett, WA",(0,1,6,0,1,3,0,0),(68,64,82,72,62,62,92,64,90,55),["Wrestler","Boring But Effective"],["Wholesome","Business Savvy"],"The Ageless Grinder","wrestler",["dirtyBoxing"],"none",(19,11),"Won a title in his forties and acted in movies with explosions. Still does dirty boxing on unsuspecting gym members."),
 ("tito_orteez","Tito","Orteez","The Huntington Beach Bad Boy (Now Mayor-ish)","Tito Ortiz","M",50,"lightheavy","USA","Huntington Beach, CA",(2,2,0,2,2,2,1,1),(66,74,82,66,62,74,64,70,80,55),["Wrestler","Ground & Pound"],["Showman","Trash Talker","Political","Conspiracy Poster"],"The Grave-Digger","wrestler",["groundAndPound"],"graveDig",(21,12),"Digs an imaginary grave after every win. Has opinions about everything, most of them loud."),
 ("brock_lesmar","Brock","Lesmar","The Beast (Incarnate Farm)","Brock Lesnar","M",47,"heavy","USA","Webster, SD",(0,1,4,2,2,1,2,0),(62,92,94,64,58,68,60,80,80,70),["Wrestler","Ground & Pound"],["Showman","Mercenary","Shy"],"The Crossover Monster","wrestler",["suplex"],"roar",(5,3),"Pro wrestling superstar who walked into a cage and became champion. Lives on a farm, hates press, loves money."),
 ("bj_pennandpaper","BJ","Penn-and-Paper","The Prodigy (Retired)","BJ Penn","M",45,"light","USA","Hilo, HI",(2,1,0,0,1,1,1,0),(76,68,70,92,48,72,82,66,82,55),["Sub Hunter","Counter Striker"],["Party Animal","Hothead"],"The Hawaiian Prodigy","bouncy",["bloodLick"],"licksGloves",(16,14),"Black belt in record time, champion in two divisions, and the most famous blood-licking celebration in history. Kept fighting long past the point anyone wanted him to."),
 ("matt_huge","Matt","Huge","The Farm Boy Powerbomb","Matt Hughes","M",50,"welter","USA","Hillsboro, IL",(0,1,4,0,1,1,0,0),(64,72,90,78,72,72,78,72,84,55),["Wrestler","Ground & Pound"],["Devout","Family First"],"The Old-School Champ","wrestler",["slam"],"none",(45,9),"Slammed people for a living before slamming was cool. Farm-strong, faith-strong, and not a fan of trash talk."),
 ("junior_dossantaclaus","Junior","Dos Santa-Claus","Cigano (Gypsy Jazz)","Junior dos Santos","M",40,"heavy","Brazil","Cacador",(2,2,0,2,2,1,0,0),(86,88,62,64,66,70,74,74,82,55),["Brawler","Counter Striker"],["Wholesome"],"The Smiling Boxer","upright",["overhandRight"],"smiles",(21,9),"Heavyweight boxer with a permanent smile and an overhand right that ended careers. Nicest heavyweight to ever knock you out."),
 ("wanderlie_silvah","Wanderlie","Silvah","The Axe Murderer (Hatchet)","Wanderlei Silva","M",48,"middle","Brazil","Curitiba",(2,0,0,0,1,3,1,2),(78,84,58,62,60,64,64,64,92,55),["Brawler","Muay Thai"],["Showman","Hothead"],"The Pride Legend","brawler",["soccerKick","muayThaiKnees"],"none",(35,14),"A legend of the old Japanese rings where stomping was legal and knees were a love language. His stare-downs could curdle milk."),
 ("shogun_ruah","Shogun","Ruah","The Leg Kick Grandpa","Mauricio Rua","M",42,"lightheavy","Brazil","Curitiba",(2,2,0,1,1,2,1,1),(78,82,62,72,60,66,76,64,90,55),["Muay Thai","Brawler"],["Wholesome","Loyal"],"The Pride Legend","upright",["legKicks","soccerKick"],"none",(27,13),"Destroyed legs for a living and never once complained about his own knees, which are held together by staples and optimism."),
 ("lyoto_matchada","Lyoto","Matcha-Da","The Dragon (Tea)","Lyoto Machida","M",46,"lightheavy","Brazil","Salvador",(1,2,0,0,0,0,0,0),(86,74,72,76,74,72,90,72,80,55),["Counter Striker","Karate" if False else "Kickboxer"],["Devout","Shy"],"The Karate Mystic","karate",["craneKick","frontKick"],"bows",(26,12),"Karate master who drank... a famous morning beverage for health reasons that we will not describe. Front kicks you in the face with a peaceful expression."),
 ("rashad_even","Rashad","Even","Suga (Free)","Rashad Evans","M",45,"lightheavy","USA","Niagara Falls, NY",(4,1,0,1,1,1,0,0),(74,76,84,70,68,74,78,74,80,55),["Wrestler"],["Showman","Business Savvy"],"The Smooth Talker","bouncy",["overhandRight"],"none",(19,8),"Smooth talker, smooth wrestler, smooth transition to broadcasting."),
 ("rampage_jaxon","Rampage","Jaxon","Rampage (Howling)","Quinton Jackson","M",46,"lightheavy","USA","Memphis, TN",(5,0,0,1,2,1,1,0),(72,86,66,54,58,76,62,76,82,70),["Brawler"],["Prankster","Showman"],"The Chain-Wearing Howler","brawler",["slam"],"howls",(38,14),"Howls at the crowd, wears a giant chain, and once slammed a man so hard the arena felt it. A legendary practical joker with terrible impulse control."),
 ("forrest_griffon","Forrest","Griffon","The Accidental Legend","Forrest Griffin","M",44,"lightheavy","USA","Athens, GA",(0,2,1,1,1,1,0,1),(70,68,72,68,74,74,70,74,92,55),["Brawler"],["Prankster","Wholesome"],"The Everyman Hero","brawler",["volume"],"none",(19,7),"Won a reality show with a fight so bloody it made the sport mainstream. Writes self-deprecating books. The most relatable champion ever."),
 ("dan_hendoson","Dan","Hendo-Son","The H-Bomb (Hydrogen)","Dan Henderson","M",53,"middle","USA","Downey, CA",(0,1,6,0,1,2,0,1),(70,90,82,62,62,70,78,70,90,55),["Wrestler","Brawler"],["Loyal","Shy"],"The H-Bomb","wrestler",["overhandRight"],"none",(32,15),"Olympic wrestler with the most famous right hand in history. Retired at 46 after nearly winning the belt one last time."),
 ("nick_diazz","Nick","Diazz","The Original Stockton Slapper","Nick Diaz","M",40,"welter","USA","Stockton, CA",(1,2,0,2,0,2,2,1),(82,68,50,88,94,82,76,78,92,40),["Brawler","Sub Hunter"],["Hothead","Trash Talker","Paranoid","Party Animal"],"The Original Bad Boy","brawler",["stocktonSlap","mockery"],"shrug",(26,10),"The older brother and the original. Mocked opponents mid-fight, skipped every press event he could, and somehow became a legend for it."),
 ("frankie_edgy","Frankie","Edgy","The Answer (Unclear)","Frankie Edgar","M",42,"feather","USA","Toms River, NJ",(0,2,0,1,0,1,0,1),(80,64,84,74,92,80,86,78,96,55),["Wrestler","Point Fighter"],["Wholesome","Family First"],"The Undersized Warrior","bouncy",["comebacks"],"none",(24,11),"Fought giants his whole career and never once complained. The definition of 'heart over size'."),
 ("jose_aldough","Jose","Aldough","Scarface (Smaller Face)","Jose Aldo","M",38,"feather","Brazil","Manaus",(3,1,0,0,0,0,0,0),(92,82,74,74,78,80,90,80,90,55),["Muay Thai","Counter Striker"],["Loyal","Shy"],"The Featherweight King","upright",["legKicks"],"runsIntoCrowd",(31,8),"The original featherweight king. Leg kicks that ended careers and a famous sprint into the crowd after a home win."),
 ("urijah_fibber","Urijah","Fibber","The California Kid (Adult)","Urijah Faber","M",45,"bantam","USA","Sacramento, CA",(0,2,4,0,0,1,0,0),(76,70,82,84,82,76,78,74,86,55),["Wrestler","Sub Hunter"],["Business Savvy","Showman","Wholesome"],"The Team Builder","bouncy",["guillotine"],"none",(35,11),"Built a gym empire and a hairstyle that has not moved since 2006."),
 ("dominick_crews","Dominick","Crews","The Dominator (Analyst)","Dominick Cruz","M",39,"bantam","USA","San Diego, CA",(2,2,0,0,0,0,0,0),(88,64,72,66,86,76,94,66,86,55),["Point Fighter","Counter Striker"],["Perfectionist","Business Savvy"],"The Footwork Genius","sway",["footwork"],"none",(24,4),"Moves in angles that confused opponents and scientists. Now explains footwork on television for forty-minute stretches."),
 ("demetrious_johnsun","Demetrious","Johnsun","Mighty Mouse (Mighty Mild)","Demetrious Johnson","M",38,"fly","USA","Kirkland, WA",(4,1,0,0,0,0,0,0),(88,64,88,90,96,80,99,80,88,55),["Wrestler","Sub Hunter"],["Gym Rat","Wholesome","Shy"],"The Flyweight GOAT","bouncy",["suplexToArmbar"],"none",(31,4),"So technically perfect that his greatest weakness was 'being too small for people to notice'. Streams video games and is better at those too."),
 ("daniel_cornmayor","Daniel","Corn-Mayor","DC (Dad Comedian)","Daniel Cormier","M",45,"heavy","USA","Lafayette, LA",(5,0,0,2,2,3,0,0),(76,76,94,78,72,80,88,78,90,60),["Wrestler"],["Trash Talker","Wholesome","Showman"],"The Commentator Champ","wrestler",["doubleLeg"],"none",(22,3),"Two-division champion turned commentator who will remind you he's a two-division champion during unrelated commercial breaks."),
 ("stipe_miosick","Stipe","Mio-Sick","The Firefighter (Part-Time)","Stipe Miocic","M",42,"heavy","USA","Euclid, OH",(0,1,1,1,2,1,0,1),(82,82,82,70,76,84,84,82,92,55),["Wrestler","Brawler"],["Wholesome","Loyal","Family First"],"The Working-Class Hero","upright",["overhandRight"],"none",(20,4),"The most successful heavyweight champion in history, who also kept his job as a part-time firefighter, which is the most Ohio thing ever."),
 ("amanda_nunez","Amanda","Nunez","The Lioness (Kitten)","Amanda Nunes","W",37,"wbantam","Brazil","Salvador",(3,6,0,0,1,1,1,0),(90,92,80,86,80,84,86,86,90,60),["Brawler","Sub Hunter"],["Showman","Family First"],"The Women's GOAT","upright",["rightHand"],"roar",(23,5),"Two-division champion widely considered the greatest female fighter ever. Retired on top to raise her family."),
 ("ronda_rowdysey","Ronda","Rowdysey","Rowdy (Retired)","Ronda Rousey","W",37,"wbantam","USA","Riverside, CA",(0,5,4,0,1,1,0,0),(60,70,88,94,72,58,72,64,82,60),["Judoka","Sub Hunter"],["Showman","Trash Talker","Mercenary"],"The Pioneer","upright",["armbar"],"none",(12,2),"Made the sport take women's MMA seriously with an armbar nobody could stop. Then left for movies and pro wrestling."),
 ("holly_home","Holly","Home","The Preacher's Daughter","Holly Holm","W",42,"wbantam","USA","Albuquerque, NM",(0,5,4,0,0,0,0,0),(88,74,64,62,80,80,86,74,86,55),["Kickboxer","Counter Striker"],["Devout","Wholesome"],"The Head-Kick Hero","upright",["headKick"],"prays",(15,7),"World champion boxer who pulled off one of the biggest upsets in sports history with a head kick."),
 ("miesha_tater","Miesha","Tater","Cupcake (Muffin)","Miesha Tate","W",37,"wbantam","USA","Tacoma, WA",(0,5,2,0,1,1,0,0),(68,64,82,84,80,76,74,76,90,55),["Wrestler","Sub Hunter"],["Showman","Trash Talker"],"The Rivalry Queen","wrestler",["rearNakedChoke"],"none",(19,9),"Built a career on rivalries and comebacks, including choking out a champion in the last minute of a title fight."),
 ("joanna_jedrzewhat","Joanna","Jedrze-What","Joanna Champion (Of Spelling)","Joanna Jedrzejczyk","W",36,"wstraw","Poland","Olsztyn",(0,5,4,0,0,0,0,0),(92,70,62,62,90,76,86,72,90,55),["Muay Thai","Pressure Striker"],["Trash Talker","Showman"],"The Volume Queen","upright",["volumeStriking"],"none",(16,5),"Muay Thai world champion whose name defeated more commentators than opponents. Volume striking, terrifying stare-downs."),
 ("mark_coalman","Mark","Coalman","The Hammer (Ground & Pound Inventor)","Mark Coleman","M",59,"heavy","USA","Fremont, OH",(0,1,4,0,2,2,0,0),(54,70,86,60,52,64,66,64,82,55),["Wrestler","Ground & Pound"],["Wholesome"],"The Godfather of Ground & Pound","wrestler",["groundAndPound"],"none",(16,10),"Basically invented lying on people and punching them. The sport owes him a royalty check."),
 ("ken_shamwow","Ken","Shamwow","The World's Most Dangerous Man (Sunday Brunch Edition)","Ken Shamrock","M",60,"lightheavy","USA","Susanville, CA",(0,1,4,0,1,1,0,1),(56,66,74,76,52,60,70,60,84,55),["Sub Hunter"],["Showman","Mercenary"],"The Old-School Legend","wrestler",["kneebar"],"none",(28,17),"The original 'World's Most Dangerous Man'. Still fights in exhibitions at an age when most people fight with their HOA."),
 ("royce_grazie","Royce","Grazie","The Original (Gi)","Royce Gracie","M",57,"middle","Brazil","Rio de Janeiro",(1,2,0,0,0,0,0,0),(48,48,70,96,70,62,92,58,90,55),["Sub Hunter"],["Loyal","Devout"],"The Founding Father","upright",["triangle"],"bows",(15,2),"Skinny guy in a gi who beat everyone at the very first tournament and changed martial arts forever."),
 ("dan_severe","Dan","Severe","The Beast (Moustache Edition)","Dan Severn","M",66,"heavy","USA","Coldwater, MI",(0,1,6,4,2,1,0,0),(48,58,84,64,50,60,64,62,80,55),["Wrestler"],["Wholesome","Shy"],"The Moustache","wrestler",["suplex"],"none",(101,19),"Has more fights than most promotions. Has the most respectable moustache in combat sports history."),
 ("mark_hunted","Mark","Hunted","Super Samoan (Walk-Off Edition)","Mark Hunt","M",50,"heavy","New Zealand","Auckland",(4,1,0,1,2,2,2,1),(84,94,52,52,48,96,72,90,90,70),["Brawler"],["Wholesome","Shy"],"The Walk-Off King","upright",["walkOffKO"],"walksAway",(13,14),"Famous for knocking people out and walking away before they hit the ground. Chin made of volcanic rock."),
 ("alistair_overeat","Alistair","Overeat","The Reem (Ream)","Alistair Overeem","M",44,"heavy","Netherlands","Hounslow",(0,1,0,1,2,2,2,1),(86,86,62,74,62,58,80,62,78,60),["Kickboxer","Muay Thai"],["Showman","Business Savvy"],"The Kickboxing Giant","upright",["knees"],"none",(47,19),"Won every belt in every promotion on earth, often looking like a different person each time."),
 ("andrei_arlovski","Andrei","Arlov-Ski","The Pitbull (Chihuahua)","Andrei Arlovski","M",45,"heavy","Belarus","Babruysk",(0,2,1,0,2,1,0,1),(82,80,60,62,70,58,80,64,90,55),["Kickboxer","Brawler"],["Wholesome","Loyal"],"The Iron Veteran","upright",["straightRight"],"none",(34,22),"Has fought in every decade of the sport's existence and simply refuses to stop."),
 ("big_noggin","Antonio","Noggin","Big Nog (Bigger Noggin)","Antonio Rodrigo Nogueira","M",48,"heavy","Brazil","Vitoria da Conquista",(2,2,0,1,2,2,0,1),(70,72,70,94,60,82,86,74,96,55),["Sub Hunter"],["Wholesome","Loyal"],"The Comeback Submission King","upright",["armbar"],"none",(34,10),"Got beaten up for two rounds every fight and then submitted you in the third with a smile."),
 ("vitor_bellfort","Vitor","Bellfort","The Phenom (Phenomenally Jacked)","Vitor Belfort","M",47,"middle","Brazil","Rio de Janeiro",(2,1,0,0,1,1,1,0),(84,90,68,74,62,64,72,70,80,55),["Brawler"],["Devout","Conspiracy Poster","Showman"],"The Blitz","upright",["blitz","spinningHeelKick"],"none",(26,14),"Fastest hands of his era and a spinning heel kick everybody still remembers."),
 ("rich_frankfurter","Rich","Frankfurter","Ace (Of Spades)","Rich Franklin","M",49,"middle","USA","Cincinnati, OH",(0,1,4,0,1,1,0,1),(80,74,66,70,76,74,84,72,86,55),["Kickboxer"],["Wholesome","Business Savvy"],"The Math Teacher Champion","upright",["kneesInClinch"],"none",(29,7),"Former high-school math teacher who became champion and stayed exactly that nice."),
 ("chris_wideman","Chris","Wideman","The All-American (Shin Edition)","Chris Weidman","M",40,"middle","USA","Baldwin, NY",(0,2,1,0,1,1,0,0),(72,74,86,82,74,66,78,62,90,55),["Wrestler"],["Family First","Wholesome"],"The Upset Artist","wrestler",["doubleLeg"],"none",(16,7),"Ended an all-time great reign, then suffered more misfortune than anyone deserved. Keeps showing up."),
 ("luke_rockhole","Luke","Rockhole","Rock-Hole (Model Edition)","Luke Rockhold","M",39,"middle","USA","Santa Cruz, CA",(0,3,1,1,0,0,0,0),(80,74,76,84,76,58,80,62,78,55),["Kickboxer","Sub Hunter"],["Diva","Trash Talker","Showman"],"The Model Fighter","upright",["bodyKick"],"none",(16,6),"Champion, model, and the most strongly opinionated man about other people's training methods."),
 ("robbie_lawlessr","Robbie","Lawless-er","Ruthless (Mostly)","Robbie Lawler","M",42,"welter","USA","Bettendorf, IA",(0,1,4,0,1,2,1,1),(84,86,66,64,76,84,78,84,98,55),["Brawler","Pressure Striker"],["Shy","Loyal"],"The Ruthless Veteran","upright",["leftHand"],"none",(29,16),"Fought the bloodiest five-round war in history and then smiled with a split lip. Says nothing. Means everything."),
 ("donald_cerrownie","Donald","Cerrownie","Cowboy (Ranch Dressing)","Donald Cerrone","M",41,"light","USA","Denver, CO",(0,2,2,1,1,2,2,0),(80,74,62,82,72,72,76,72,84,55),["Kickboxer","Sub Hunter"],["Party Animal","Wholesome","Gambler"],"The Anytime Fighter","upright",["headKick"],"tipsHat",(36,17),"Would fight anyone, anywhere, on two weeks' notice, then go wakeboarding the next morning."),
 ("joe_lozenge","Joe","Lozenge","J-Lo (Not That One)","Joe Lauzon","M",40,"light","USA","Bridgewater, MA",(0,1,5,0,1,1,0,1),(70,66,66,86,70,70,76,74,88,55),["Sub Hunter"],["Wholesome","Gym Rat"],"The Bonus Machine","upright",["kneebar"],"none",(28,16),"Holds the record for most fight-night bonuses by a man who also works in IT."),
 ("clay_guidance","Clay","Guidance","The Carpenter (Hair)","Clay Guida","M",42,"light","USA","Johnsburg, IL",(0,5,2,3,0,1,0,0),(64,62,82,74,96,80,70,80,96,55),["Wrestler","Pressure Striker"],["Wholesome","Gym Rat"],"The Human Energy Drink","bouncy",["bounce"],"none",(37,17),"The most cardio in human history and the most hair. Literally never stops moving."),
 ("diego_sanchezyes","Diego","Sanchez-YES","The Nightmare (YES Cartel)","Diego Sanchez","M",43,"welter","USA","Albuquerque, NM",(2,2,0,1,1,2,1,1),(66,66,74,76,82,72,58,78,99,55),["Brawler","Wrestler"],["Showman","Conspiracy Poster","Devout"],"The Spiritual Warrior","brawler",["yesChant"],"yesChant",(31,13),"Walks out screaming 'YES', trains on mountaintops, and once fought with a cut so bad the doctor needed a doctor."),
 ("anthony_petis","Anthony","Pet-Is","Showtime (Showtime Kick)","Anthony Pettis","M",37,"light","USA","Milwaukee, WI",(2,2,0,0,0,0,1,0),(86,76,58,78,72,70,80,68,82,55),["Kickboxer","Showboat"],["Showman","Wholesome"],"The Highlight Kicker","karate",["showtimeKick","spinningBackKick"],"none",(25,13),"Ran up the cage and kicked a man in the face. The sport has been trying to recreate it ever since."),
 ("benson_hendersun","Benson","Hender-Sun","Smooth (Toothpick)","Benson Henderson","M",40,"light","USA","Glendale, AZ",(3,1,0,0,1,1,0,0),(78,66,82,82,90,80,84,80,90,55),["Wrestler","Point Fighter"],["Devout","Wholesome"],"The Toothpick Champ","upright",["guillotine"],"pointsUp",(30,12),"Fought with a toothpick in his mouth and won a lot of very close decisions. Nobody knows what happened to the toothpicks."),
 ("eddie_alvarezz","Eddie","Alvarezz","The Underground King (Basement)","Eddie Alvarez","M",40,"light","USA","Philadelphia, PA",(0,1,1,1,1,2,1,1),(80,82,76,72,76,80,80,78,92,55),["Brawler","Wrestler"],["Trash Talker","Loyal"],"The Philly Brawler","upright",["leftHook"],"none",(30,8),"Philadelphia street fighter who won titles in multiple promotions and refuses to stop throwing hands."),
 ("rafael_dosangels","Rafael","Dos Angels","RDA (Really Dangerous Anytime)","Rafael dos Anjos","M",40,"light","Brazil","Niteroi",(2,1,0,1,1,2,0,0),(80,74,74,86,84,78,82,80,88,55),["Muay Thai","Sub Hunter"],["Loyal","Wholesome"],"The Veteran Grinder","upright",["legKicks"],"none",(32,15),"Former champion who has fought everyone in three divisions and is still asking for more."),
 ("mirko_crowcop","Mirko","Crow Cop","Right Leg Hospital, Left Leg Cemetery","Mirko Cro Cop","M",50,"heavy","Croatia","Vinkovci",(0,1,1,0,1,1,0,1),(84,86,62,60,62,70,80,70,84,55),["Kickboxer"],["Shy","Political"],"The Head-Kick Legend","upright",["leftHeadKick"],"none",(38,11),"Former police officer and politician whose left head kick had its own obituary section."),
 ("gegard_mooseasi","Gegard","Moose-Asi","The Dreamcatcher (Nightmare Edition)","Gegard Mousasi","M",39,"middle","Netherlands","Leiden",(1,1,0,1,1,1,0,0),(84,76,74,84,72,78,90,78,82,55),["Counter Striker","Sub Hunter"],["Shy","Business Savvy"],"The Unbothered Veteran","upright",["jab"],"none",(49,8),"So calm he looks like he's sleepwalking. Has beaten everyone, everywhere, while looking mildly inconvenienced."),
 ("bas_rotten","Bas","Rotten","El Guapo (El Gross)","Bas Rutten","M",59,"heavy","Netherlands","Tilburg",(0,0,0,1,1,2,2,1),(76,78,60,74,60,74,82,72,90,55),["Kickboxer","Sub Hunter"],["Showman","Prankster","Wholesome"],"The Legendary Storyteller","upright",["liverShot"],"none",(28,4),"Never lost in his last 22 fights. Now tells stories about bar fights that may or may not have happened, with sound effects."),
 ("pat_milewitch","Pat","Mile-Witch","The Croatian Sensation (Iowa)","Pat Miletich","M",56,"welter","USA","Bettendorf, IA",(0,1,4,4,1,1,0,1),(70,64,76,80,70,72,88,70,84,55),["Sub Hunter"],["Mentor","Shy"],"The Coach","upright",["guillotine"],"none",(29,7),"Early welterweight champion who built the most feared gym in the Midwest."),
 ("jens_pulverize","Jens","Pulverize","Little Evil (Medium Evil)","Jens Pulver","M",49,"light","USA","Sunnyside, WA",(0,1,4,0,0,1,1,1),(80,78,58,52,70,70,70,70,86,55),["Brawler"],["Wholesome","Paranoid"],"The First Lightweight","upright",["leftHand"],"none",(27,20),"The first lightweight champion of the modern era, with a left hand that hit far above its weight."),
 ("kazushi_sakuraba","Kazushi","Sakura-Baba","The Gracie Hunter (Gracie Hobbyist)","Kazushi Sakuraba","M",55,"middle","Japan","Akita",(0,2,0,0,1,2,0,0),(64,62,74,92,68,72,92,70,96,55),["Sub Hunter","Showboat"],["Showman","Prankster"],"The Showman Grappler","upright",["kimura","windmillPunches"],"none",(26,17),"Wore masks to the ring, fought for 90 minutes straight, and made submission grappling look like improv comedy."),
 ("cung_lee","Cung","Lee-ish","The Kickboxing Movie Star","Cung Le","M",52,"middle","USA","San Jose, CA",(1,1,0,0,1,0,0,0),(84,76,66,56,66,70,78,70,80,55),["Kickboxer","Showboat"],["Showman"],"The Spinning Kicker","karate",["spinningBackKick"],"none",(9,3),"San shou champion whose spinning back kicks were so fast that VCR tapes couldn't keep up."),
 ("gina_carry-no","Gina","Carry-No","Conviction (Hollywood)","Gina Carano","W",42,"wbantam","USA","Dallas, TX",(1,5,1,0,1,0,0,0),(76,70,62,58,64,68,70,64,78,55),["Muay Thai"],["Showman","Political"],"The Face of Women's MMA (First Draft)","upright",["muayThaiClinch"],"none",(7,1),"Before anyone took women's MMA seriously, she was on magazine covers and action movie sets."),
]


def look(t):
    skin, hair, hc, beard, build, ears, tattoo, nose = t
    return {"head": (sum(map(ord, str(t))) % 4), "skin": skin, "hair": hair, "hairColor": hc, "beard": beard, "brows": 1, "eyes": 0,
            "nose": nose, "ears": ears, "scar": 1 if ears >= 2 else 0, "tattoo": tattoo, "build": build}


def skills(t):
    k = ["striking", "power", "wrestling", "grappling", "cardio", "chin", "fightIQ", "durability", "heart", "weightCut"]
    return dict(zip(k, t))


def entry(r, legend=False):
    if legend:
        (id_, first, last, nick, parody, g, age, div, country, home, lk, sk, styles, traits, arch, stance, sig, cel, rec, bio) = r
        debut, start, pot, prime, money, followers = 1, "free", max(sk[:8]) , 29, 60, 500000
    else:
        (id_, first, last, nick, parody, g, age, div, country, home, lk, sk, styles, traits, arch, stance, sig, cel, rec, debut, start, pot, prime, money, followers, bio) = r
    o = {
        "id": id_, "first": first, "last": last, "nick": nick, "gender": g, "age": age, "division": div,
        "country": country, "hometown": home, "look": look(lk), "skills": skills(sk), "styles": styles, "traits": traits,
        "marquee": {"archetype": arch, "arc": arch}, "anim": {"stance": stance, "signature": sig, "celebration": cel},
        "record": {"w": rec[0], "l": rec[1], "d": 0, "nc": 0}, "potential": pot, "primeAge": prime, "moneyIQ": money,
        "social": {"followers": followers, "style": "gym selfies"}, "bio": bio, "hiddenTraits": [],
    }
    if parody:
        o["parody"] = parody
    if legend:
        o["legend"] = True
        o["status"] = "retired"
        o["marquee"]["arc"] = "legend"
    else:
        o["debutAct"] = debut
        o["startWith"] = start
    if "Streamer" in traits:
        o["social"]["style"] = "live streams"
    elif "Trash Talker" in traits:
        o["social"]["style"] = "all caps rants"
    elif "Devout" in traits:
        o["social"]["style"] = "prayer emojis"
    elif "Conspiracy Poster" in traits:
        o["social"]["style"] = "conspiracy threads"
    return o


marquee = [entry(r) for r in M]
legends = [entry(r, True) for r in L]
json.dump({"note": "Marquee characters. Parodies carry 'parody'. Edit freely.", "fighters": marquee}, open(os.path.join(ROOT, "data/roster/marquee.json"), "w"), indent=1)
json.dump({"note": "Retired legends. Available for comebacks, commentary and the Hall of Fame.", "fighters": legends}, open(os.path.join(ROOT, "data/roster/legends.json"), "w"), indent=1)
print(len(marquee), "marquee,", len(legends), "legends")
